apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1 # Number of replicas you want
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: shubhamxshah/api-bopro:654073baec62f4913068ba31d14d4edd85cc1e6f
          ports:
            - containerPort: 3001
          env: # Correct placement of the env section
            - name: REDIS_HOST
              value: "redis://redis-service:6379"
              

