apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1 # Number of replicas you want
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: shubhamxshah/api-bopro:7e110ec3b969f848c6560219dd5b45200a260272
          ports:
            - containerPort: 3000
          env: # Correct placement of the env section
            - name: REDIS_HOST
              value: "redis://redis-service:6379"
              

