apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ClusterIP # Internal service, accessible only within the cluster
  ports:
    - port: 3000            # Port on which the service is exposed
      targetPort: 3000      # Port on which the container is running
  selector:
    app: api

