apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: shubhamxshah/db-bopro:b0f3f60542b6ad0f13230157b8a5233ac028586c
          env:
            - name: REDIS_HOST
              value: "redis://redis-service:6379"
            - name: DATABASE_URL
              value: "postgresql://neondb_owner:rYZpMqxBt08d@ep-yellow-frost-a4jy60op.us-east-1.aws.neon.tech/neondb?sslmode=require"

