apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
      - name: engine
        image: shubhamxshah/engine-bopro:654073baec62f4913068ba31d14d4edd85cc1e6f
        env:
        - name: REDIS_HOST
          value: "redis://redis-service:6379"

