apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
      - name: engine
        image: shubhamxshah/engine-bopro:7568edfa458286c535590d23f50a2d7311c27f0d
        env:
        - name: REDIS_HOST
          value: "redis://redis-service:6379"

