apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
      - name: engine
        image: shubhamxshah/engine-bopro:cbff9f43dce2075fe3ed4e0ffdefeb3d079ad27d
        env:
        - name: REDIS_HOST
          value: "redis://redis-service:6379"

