apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
      - name: engine
        image: shubhamxshah/engine-bopro:7e110ec3b969f848c6560219dd5b45200a260272
        env:
        - name: REDIS_HOST
          value: "redis://redis-service:6379"

