apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
      - name: engine
        image: shubhamxshah/engine-bopro:2c6733198e305adc63a5e9ef647b458d5468470e
        env:
        - name: REDIS_HOST
          value: "redis://redis-service:6379"

