apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
      - name: engine
        image: shubhamxshah/engine-bopro:a07e7b56e3596ce554a8cd3055fd8512de43a3e2
        env:
        - name: REDIS_HOST
          value: "redis://redis-service:6379"

