apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1 # Number of replicas you want
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: api
          image: shubhamxshah/frontend-bopro:fcede2cfb4a14fd9d8990aabeba1b5664220c54b
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP # Internal service, accessible only within the cluster
  ports:
    - port: 3000            # Port on which the service is exposed
      targetPort: 3000     # Port on which the container is running
  selector:
    app: frontend

