apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws2
  labels:
    app: ws2
spec:
  replicas: 1 # Number of replicas you want
  selector:
    matchLabels:
      app: ws2
  template:
    metadata:
      labels:
        app: ws2
    spec:
      containers:
        - name: ws2
          image: shubhamxshah/ws2-bopro:latest # Replace with your actual Docker image and tag
          ports:
            - containerPort: 8080
          env: # Correct placement of the env section
            - name: REDIS_HOST
              value: "redis://redis-service:6379"
              


