apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ClusterIP # Internal service, accessible only within the cluster
  ports:
    - port: 8080            # Port on which the service is exposed
      targetPort: 8080      # Port on which the container is running
  selector:
    app: api


